version: "3.8"

services:
  torch-notebook:
    image: trinhngoccac/pytorch-notebook
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.service == data_worker]
    command: start-notebook.sh --ServerApp.password='' --ServerApp.token=''
    ports:
      - 8888:8888
    volumes:
      - ./resource:/home/jovyan/work/resource
      - ./src:/home/jovyan/work/src

  fastapi:
    image: trinhngoccac/py-with-fastapi
    deploy:
      replicas: 3
      placement:
        constraints: [node.labels.service == web_worker]
    command: fastapi run main_scripts/api_main.py
    ports:
      - 8000:8000
    volumes:
      - ./resource:/home/resource
      - ./src/utils:/home/work/utils
      - ./src/api:/home/work/api
      - ./src/main_scripts:/home/work/main_scripts