version: "3.8"

services:
  torch-notebook:
    image: trinhngoccac/pytorch-notebook
    command: start-notebook.sh --ServerApp.password='sha1:57d81e0f255f:4205c21b8e736e244e8677d3758acc9bfdefe977'
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - 8888:8888
    volumes:
      - ./resource:/home/jovyan/work/resource
      - ./src:/home/jovyan/work/src
  web:
    image: trinhngoccac/py-with-fastapi
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    ports:
      - 8000:80
    volumes:
      - ./resource:/home/work/resource
      - ./src/app:/home/work/app